using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace LB.TweenHelper.Editor
{
    public static class BuiltInPresetRegistrationExporter
    {
        [MenuItem("Tools/Tween Helper Dev/Export Built-in Preset Registration")]
        public static void Export()
        {
            Type[] types = typeof(TweenPresetRegistry).Assembly.GetTypes()
                .Where(type => !type.IsAbstract && typeof(CodePreset).IsAssignableFrom(type) && type.GetCustomAttribute<AutoRegisterPresetAttribute>() != null)
                .OrderBy(type => type.Name, StringComparer.Ordinal).ToArray();
            var source = new StringBuilder();
            source.AppendLine("// Generated by the development preset registration exporter.");
            source.AppendLine("namespace LB.TweenHelper");
            source.AppendLine("{");
            source.AppendLine("    internal static class BuiltInPresetRegistration");
            source.AppendLine("    {");
            source.AppendLine("        internal static int Register()");
            source.AppendLine("        {");
            foreach (Type type in types)
            {
                if (type.Namespace != "LB.TweenHelper" || type.GetConstructor(Type.EmptyTypes) == null)
                    throw new InvalidOperationException($"Built-in preset '{type.FullName}' requires the LB.TweenHelper namespace and a public parameterless constructor.");
                source.AppendLine($"            TweenPresetRegistry.RegisterPreset(new {type.Name}());");
            }
            source.AppendLine($"            return {types.Length};");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            const string path = "Assets/Loags/TweenHelper/Runtime/Core/BuiltInPresetRegistration.cs";
            File.WriteAllText(path, source.ToString().Replace("\r\n", "\n"), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(path);
            Debug.Log($"Exported {types.Length} built-in preset registrations.");
        }
    }
}
